from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
                                KeepTogether, Flowable)
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import os

OUT = os.path.join(os.path.dirname(__file__), 'output', 'pdf', 'EDUVORA_Project_Report_Indrasish_Biswas.pdf')
os.makedirs(os.path.dirname(OUT), exist_ok=True)

NAVY = HexColor('#172554')
BLUE = HexColor('#2563EB')
PALE = HexColor('#EFF6FF')
SLATE = HexColor('#334155')
GREY = HexColor('#64748B')
LINE = HexColor('#CBD5E1')

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='BodyX', parent=styles['BodyText'], fontName='Helvetica', fontSize=10.2,
    leading=15.2, alignment=TA_JUSTIFY, textColor=SLATE, spaceAfter=8))
styles.add(ParagraphStyle(name='Small', parent=styles['BodyText'], fontName='Helvetica', fontSize=8.6,
    leading=11.5, textColor=SLATE))
styles.add(ParagraphStyle(name='H1X', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=17,
    leading=22, textColor=NAVY, spaceBefore=2, spaceAfter=12, keepWithNext=True))
styles.add(ParagraphStyle(name='H2X', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=12.2,
    leading=16, textColor=BLUE, spaceBefore=10, spaceAfter=7, keepWithNext=True))
styles.add(ParagraphStyle(name='TitleX', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=26,
    leading=32, textColor=NAVY, alignment=TA_CENTER))
styles.add(ParagraphStyle(name='CoverSub', parent=styles['BodyText'], fontName='Helvetica', fontSize=13,
    leading=18, textColor=SLATE, alignment=TA_CENTER))
styles.add(ParagraphStyle(name='Cap', parent=styles['BodyText'], fontName='Helvetica-Oblique', fontSize=8.8,
    leading=11, alignment=TA_CENTER, textColor=GREY, spaceBefore=5, spaceAfter=8))

def P(text, style='BodyX'): return Paragraph(text, styles[style])
def title(text): return P(text, 'H1X')
def h2(text): return P(text, 'H2X')
def bullets(items):
    return [Paragraph('&bull; ' + x, styles['BodyX']) for x in items]

def table(data, widths=None, fs=8.5):
    rows=[]
    for ridx,row in enumerate(data):
        rows.append([Paragraph(str(cell), ParagraphStyle('t', parent=styles['Small'], fontName='Helvetica-Bold' if ridx==0 else 'Helvetica', fontSize=fs, leading=fs+3, textColor=colors.white if ridx==0 else SLATE)) for cell in row])
    t=Table(rows, colWidths=widths, repeatRows=1, hAlign='LEFT')
    t.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('GRID',(0,0),(-1,-1),0.35,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),
        ('BACKGROUND',(0,1),(-1,-1),colors.white),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white, PALE]),
        ('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)
    ]))
    return t

class ScreenshotBox(Flowable):
    def __init__(self, label, detail, height=260):
        Flowable.__init__(self); self.label=label; self.detail=detail; self.height=height; self.width=460
    def wrap(self, aw, ah): self.width=aw; return aw,self.height
    def draw(self):
        c=self.canv; c.saveState(); c.setStrokeColor(BLUE); c.setLineWidth(1.2); c.setDash(6,4)
        c.setFillColor(HexColor('#F8FAFC')); c.roundRect(0,0,self.width,self.height,8,stroke=1,fill=1)
        c.setDash(); c.setFillColor(BLUE); c.setFont('Helvetica-Bold',11); c.drawCentredString(self.width/2,self.height/2+12,'[SCREENSHOT REQUIRED: '+self.label+']')
        c.setFillColor(SLATE); c.setFont('Helvetica',9); words=self.detail.split(); lines=[]; line=''
        for word in words:
            if stringWidth(line+' '+word,'Helvetica',9) > self.width-50: lines.append(line); line=word
            else: line=(line+' '+word).strip()
        lines.append(line); y=self.height/2-10
        for line in lines: c.drawCentredString(self.width/2,y,line); y-=13
        c.restoreState()

class Architecture(Flowable):
    def __init__(self): Flowable.__init__(self); self.width=460; self.height=260
    def wrap(self,aw,ah): self.width=aw; return aw,self.height
    def draw(self):
        c=self.canv; c.saveState(); w=self.width
        boxes=[(10,180,110,45,'User Browser\nReact SPA'),(165,180,125,45,'Node.js / Express\nREST API'),(335,180,115,45,'SQL Server\nStored Procedures'),(65,70,130,45,'RabbitMQ\nCelery Message'),(265,70,150,45,'Python KYC Worker\nOpenCV + Tesseract')]
        for x,y,bw,bh,label in boxes:
            c.setFillColor(PALE); c.setStrokeColor(BLUE); c.roundRect(x,y,bw,bh,6,fill=1,stroke=1)
            c.setFillColor(NAVY); c.setFont('Helvetica-Bold',9); yy=y+bh/2+5
            for line in label.split('\n'): c.drawCentredString(x+bw/2,yy,line); yy-=12
        def arrow(x1,y1,x2,y2):
            c.setStrokeColor(SLATE); c.setFillColor(SLATE); c.setLineWidth(1); c.line(x1,y1,x2,y2); import math
            a=math.atan2(y2-y1,x2-x1); s=6; c.line(x2,y2,x2-s*math.cos(a-.45),y2-s*math.sin(a-.45)); c.line(x2,y2,x2-s*math.cos(a+.45),y2-s*math.sin(a+.45))
        arrow(120,202,165,202); arrow(290,202,335,202); arrow(220,180,130,115); arrow(195,92,265,92); arrow(340,115,390,180)
        c.setFillColor(GREY); c.setFont('Helvetica',8); c.drawCentredString(w/2,18,'Synchronous requests use the REST API; KYC tasks are published to the Celery queue and results update SQL Server and the webhook.')
        c.restoreState()

def footer(c, doc):
    if doc.page > 2:
        c.saveState(); c.setStrokeColor(LINE); c.line(2*cm,1.55*cm,A4[0]-2*cm,1.55*cm)
        c.setFont('Helvetica',8); c.setFillColor(GREY); c.drawString(2*cm,1.1*cm,'EDUVORA Project Report')
        c.drawRightString(A4[0]-2*cm,1.1*cm,f'Page {doc.page}')
        c.restoreState()

story=[]
# Cover
story += [Spacer(1,2.0*cm), P('VOCATIONAL TRAINING PROJECT REPORT', 'CoverSub'), Spacer(1,.7*cm), P('ON', 'CoverSub'), Spacer(1,.25*cm), P('EDUVORA', 'TitleX'), Spacer(1,.2*cm), P('A Full-Stack Course Access, Referral, Payment and KYC Management Platform', 'CoverSub'), Spacer(1,2.2*cm), P('Submitted by', 'CoverSub'), Spacer(1,.15*cm), P('<b>Indrasish Biswas</b><br/>Roll / Registration No.: 24E102B91<br/>B.Tech CSE', 'CoverSub'), Spacer(1,2.0*cm), P('Submitted To', 'CoverSub'), Spacer(1,.15*cm), P('<b>Subham Chakrabertty</b><br/>CEO &amp; Founder<br/>WebMetrix', 'CoverSub'), Spacer(1,1.0*cm), P('Web Development Project Category', 'CoverSub'), PageBreak()]

# Certificate
story += [Spacer(1,2*cm), P('CERTIFICATE OF SUBMISSION','TitleX'), Spacer(1,1.5*cm), P('This is to certify that the project report entitled <b>EDUVORA</b>, a full-stack web development project for course-package access, referral-network management, payments and KYC processing, has been prepared and submitted by <b>Indrasish Biswas</b> (24E102B91), B.Tech CSE, for vocational training/project evaluation at WebMetrix.', 'BodyX'), Spacer(1,.6*cm), P('The report documents the implementation available in the EDUVORA codebase, including its React frontend, Node.js backend, SQL Server stored-procedure data layer, payment workflow and asynchronous KYC worker. It is intended as a technical submission; validation of organisational approval and signatures remains with the submitting institution and reviewer.', 'BodyX'), Spacer(1,3.2*cm), P('Submitted to<br/><br/><b>Subham Chakrabertty</b><br/>CEO &amp; Founder, WebMetrix', 'CoverSub'), PageBreak()]

story += [title('ABSTRACT'), P('EDUVORA is a full-stack web application that brings together packaged learning access, referral-network visibility, user profile management, payment initiation and identity-verification workflows. The application is designed around a React single-page frontend and a Node.js/Express REST backend. It persists operational data through SQL Server stored procedures and presents authenticated users with dashboard, profile, referral, network, course, order, earnings and KYC views.'), P('The implemented KYC pathway is the project\'s most distinct end-to-end asynchronous workflow. After a protected multipart submission, the Node.js backend applies server-side format and file checks, saves documents in a temporary repository, records the submission through a stored procedure, and publishes a persistent Celery-compatible task to RabbitMQ. A Python worker then checks image dimensions, blur and exposure, masks Aadhaar QR and number regions where applicable, moves accepted files to permanent storage, updates the SQL Server status, and calls a backend webhook. The platform also integrates Google sign-in, SMTP-driven email events, an IFSC lookup and Cashfree payment-order creation with payment-status processing through a webhook.'), P('This report is intentionally evidence-based. It differentiates live backend-connected modules from frontend demonstration areas: the current order list, earnings panels and course-player curriculum contain static/mock presentation data, and the backend does not expose corresponding live endpoints in this codebase. This distinction prevents the report from overstating present functionality.'), PageBreak()]

story += [title('ACKNOWLEDGEMENT'), P('I would like to express my sincere gratitude to Subham Chakrabertty, CEO &amp; Founder of WebMetrix, for the opportunity and guidance associated with this project. I am thankful for the practical exposure to full-stack web development, payment integration, database-driven workflows and document-processing architecture that shaped EDUVORA. I also acknowledge the support of peers and faculty whose feedback helped refine the implementation and documentation.'), PageBreak()]

story += [title('TABLE OF CONTENTS'), table([['Section','Page'],['1. Introduction and project description','6'],['2. System study and requirements','8'],['3. Software requirement specification','10'],['4. System design and architecture','12'],['5. Database design','15'],['6. Implementation modules','18'],['7. Testing and verification','22'],['8. Application walkthrough and screenshot placeholders','24'],['9. Challenges and limitations','34'],['10. Conclusion, future scope and bibliography','36']], [12*cm,4*cm]), Spacer(1,.5*cm), P('Page references are based on the generated report layout; screenshot placeholders reserve space for final UI captures to be inserted manually.', 'Small'), PageBreak()]

story += [title('1. INTRODUCTION'), h2('1.1 Project Description'), P('EDUVORA is a web development project that combines customer-facing account management with the operational workflows required by a package-based learning and referral environment. Users can register or authenticate, complete personal and banking information, receive and share referral links, inspect a visualised downline network, browse packages, initiate package payments, and submit KYC documents. The backend is structured as REST routes and controllers that invoke SQL Server stored procedures; this means the core business entities and transactions are retained in the database tier rather than in JavaScript ORM models.'), h2('1.2 Problem Statement'), P('Managing registrations, profile completeness, referral relationships, paid package entitlement and identity documents across separate manual systems creates inconsistent status visibility and makes compliance workflows difficult to trace. EDUVORA addresses this by providing a single authenticated interface and a backend that records the underlying user, payment, referral and KYC actions through named database procedures.'), h2('1.3 Verified Objectives'), table([['No.','Objective','Implementation evidence'],['01','Secure account access','Standard registration/login, Google credential verification, bcrypt password hashes and signed JWTs.'],['02','Profile and referral onboarding','Profile APIs, availability check, lookup endpoints and referral assignment/list procedures.'],['03','Package purchase initiation','Active-package query plus Cashfree order creation and webhook processing.'],['04','Asynchronous KYC processing','Multer upload, SQL persistence, RabbitMQ/Celery queue, Python checks and webhook status update.']], [1.1*cm,5*cm,9.9*cm]), PageBreak()]

story += [title('2. SYSTEM STUDY'), h2('2.1 Existing and Proposed System'), P('A fragmented workflow would require separate registration records, informal referral tracking, manual document review and unconnected payment reconciliation. EDUVORA proposes a unified browser application with a common authenticated session and central SQL Server data layer. The referral and network views are driven by dedicated stored-procedure outputs, and KYC documents are handled in a controlled temporary-to-permanent storage path rather than remaining only in a browser upload.'), h2('2.2 Hardware and Software Requirements'), table([['Layer','Verified requirement / technology','Purpose'],['Client','Modern browser; JavaScript enabled','React SPA and Cashfree JavaScript checkout redirect flow.'],['Frontend','React 19, Vite 8, React Router, Redux Toolkit, Tailwind CSS','SPA, routing, shared state and visual interface.'],['Backend','Node.js, Express 5, mssql','REST routing and stored-procedure execution.'],['Database','Microsoft SQL Server','User, profile, package, order, wallet, referral and KYC data.'],['Async worker','Python, Celery, RabbitMQ, OpenCV, Tesseract, SQLAlchemy','Queued KYC quality, masking, storage and status updates.'],['Integrations','Cashfree, Google OAuth, SMTP, IFSC endpoint','Payments, sign-in, notifications and bank metadata.']], [3.2*cm,5.2*cm,7.6*cm]), h2('2.3 Scope Boundary'), P('The codebase supplies no automated test suite and no deployment manifest. The report therefore records build verification and endpoint/module inspection rather than inventing production performance figures or deployment claims.'), PageBreak()]

story += [title('3. SOFTWARE REQUIREMENT SPECIFICATION'), h2('3.1 Users and Access Model'), P('The standard client user is assigned RoleID 3 on registration. A separate frontend route exists for a super-admin creation interface, but the route itself is not protected by the application\'s ProtectedRoute wrapper; this report therefore does not claim a verified server-side administrator authorization model. Protected API endpoints use the isLoggedIn middleware, which accepts a Bearer token or cookie, verifies a JWT and places its user identity on the request.'), h2('3.2 Functional Requirements'), *bullets(['Register with full name, email, optional mobile number, password and optionally a referral code; reject duplicate or invalid referral conditions through the database procedure.', 'Log in with credentials or a Google ID token; use the returned session information in the browser session storage and Axios authorization interceptor.', 'Read and edit profile data, upload PNG/JPG profile images, and retrieve lookup data for gender, state, city and account type.', 'Read active packages and initiate a Cashfree order for an authenticated user with required contact details.', 'Submit a PAN card and selected identity document for KYC, observe KYC status, and process the request asynchronously.', 'Retrieve a referral list with server-procedure search/date filtering and retrieve network-tree and chart payloads.']), h2('3.3 Non-functional Considerations'), P('The app uses JSON HTTP APIs, a responsive React component structure, localisation keys shared by frontend and backend, structured logging and environment variables for service configuration. Actual SLA, load, uptime and accessibility measurements are not present in the repository.'), PageBreak()]

story += [title('4. SYSTEM DESIGN'), h2('4.1 System Perspective'), P('The application divides responsibilities across a browser client, Express API, SQL Server database, third-party payment/auth/email services, RabbitMQ, and a Python Celery worker. SQL stored procedures form the principal persistence/business-transaction boundary. The frontend uses Redux slices for authentication, profile, network, referral, payment and KYC state; Axios centralises base URL, credentials and authorization-header behaviour.'), Architecture(), P('Figure 1: Verified EDUVORA architecture and KYC asynchronous path.', 'Cap'), h2('4.2 Authentication and Session Flow'), P('During standard registration, the backend creates a UUID, derives a user ID and unique username, hashes the password with bcrypt (salt rounds configured as 10), and signs a one-day JWT. The database procedure performs duplicate/referral validation. Login compares the stored hash, generates a JWT and session identifier, and updates session records through a procedure. Google login verifies the supplied ID token with google-auth-library before using the corresponding database workflow. The frontend Axios interceptor sends a session identifier as a Bearer token when present and redirects after a 401 response.'), PageBreak()]

story += [title('4. SYSTEM DESIGN CONTINUED'), h2('4.3 KYC Activity Flow'), table([['Step','Actual workflow'],['1. Collect','KycVerificationContent combines personal details, document choice, upload controls, review/consent and status components.'],['2. Validate','Frontend rules are mirrored by kycBasicValidator on the server. Multer allows JPEG, PNG and PDF MIME types at the route.'],['3. Temporarily store','The KYC route looks up the TempKYC repository path from SQL Server and creates a UUID-specific directory; files are standardised by type.'],['4. Persist and queue','EV_ManageUserKYC records the submission. The Node utility posts a persistent JSON Celery task to the RabbitMQ management API.'],['5. Process','Celery checks image resolution, Laplacian-variance blur and dark/light pixel ratios. Aadhaar images additionally undergo QR and OCR-based masking.'],['6. Finalise','Accepted files move from TempKYC to KYC storage; the worker updates KYC status in SQL Server and posts the result to the Express webhook. Rejected files are deleted from temporary storage.']], [3*cm,13*cm]), h2('4.4 Payment Activity Flow'), P('The protected create-order controller first requests a generated order number through EV_ProcessCashfreePayment with the INITIATE action. It then creates a Cashfree order using the authenticated user UUID and the user\'s name, email and mobile data. The Cashfree webhook accepts gateway event data and invokes the same procedure with WEBHOOK. According to brain.md, successful processing updates order/payment states and inserts an active user-package record. Webhook signature verification is not implemented in the inspected controller, so it is not claimed as a protection.'), PageBreak()]

story += [title('5. DATABASE DESIGN'), P('EDUVORA uses Microsoft SQL Server via the Node mssql library and Python SQLAlchemy/pyodbc. The project documents its schema in backend/brain.md and uses stored procedures from its controllers. The following table summarises the principal entities relevant to implemented user-facing flows.'), table([['Entity group','Purpose and relationship'],['Tb_User and Tb_UserDesc','Core account and extended profile information, joined by UUID. Tb_BankInfo supplies bank fields.'],['Tb_Referral and Tb_UserRelationship','Sponsor/new-user assignment and referral hierarchy used by the network and referral procedures.'],['Tb_Package, Tb_Courses, Tb_Module, Tb_Lesson','Package and learning-content catalogue. The schema defines modules and lessons; current course-player UI uses mock curriculum data.'],['Tb_Order, Tb_OrderItem, Tb_Payment, Tb_Invoice','Purchase and payment lifecycle; order items link to packages and payment data retains gateway response.'],['Tb_UserPackage','Entitlement mapping inserted after a successful payment according to EV_ProcessCashfreePayment.'],['Tb_Wallet, Tb_WalletTransaction, Tb_CommissionLedger','Commission/wallet accounting model; current frontend earnings widgets are presentational sample data in this codebase.'],['Tb_UserKYC and Tb_KYCStatusMaster','One KYC record per UUID, document paths, status and rejection reason.'],['Master tables','Roles, ranks, package status, order/payment statuses, account types, gender, city, commission rules and event templates.']], [5.4*cm,10.6*cm]), h2('5.1 Important Constraints and Data Handling'), P('The KYC schema declares UUID unique per user. The registration procedure reports collisions for account identifiers and invalid/missing referral assignments. File repository locations are obtained from Tb_FileRepositoryMaster through EV_GetFileRepositoryPath. Sensitive credentials, connection-string values, JWT secrets, payment secrets and service passwords are excluded from this report.'), PageBreak()]

story += [title('5. DATABASE DESIGN CONTINUED'), h2('5.2 Stored Procedure Integration'), table([['Procedure','Controller use'],['EV_CreateUser / EV_LogIn / EV_UpdateUserSession','Registration, credential lookup and session update.'],['EV_GetUserProfile / EV_EditUser / EV_UpdateProfilePicture / EV_UpdateAboutMe','Profile retrieval and updates.'],['EV_AssignReferral / EV_GetMyReferralsList / EV_GetMyNetwork','Referral relationship, list and hierarchy/analytics retrieval.'],['EV_GetPackages','Active package retrieval.'],['EV_ProcessCashfreePayment','Initial pending order/payment records and webhook-driven payment transition.'],['EV_ManageUserKYC','KYC retrieval, submission and worker status update.'],['EV_GetFileRepositoryPath','Profile and KYC file-storage root lookup.'],['EV_GetEmailTemplate','Email service template lookup.']], [6.4*cm,9.6*cm]), h2('5.3 Commission Calculation Boundary'), P('The schema includes Tb_CommissionRuleMaster fields for commission percentage and flat amount, but the inspected Node and Python application code does not calculate commissions. The report therefore does not state a commission formula or claim that UI earnings values are calculated live. Any computation is database-side or outside this repository\'s exposed application code.'), PageBreak()]

story += [title('6. IMPLEMENTATION MODULES'), h2('6.1 Authentication and Recovery'), P('Frontend login, registration and forgot-password pages use Redux async thunks. The backend exposes /auth/register, /auth/login, /auth/logout and /auth/google, plus OTP send/verify/resend and password reset routes. OTP routines use an email-existence check, generated numeric OTP, expiry configuration and SMTP email templates. Password reset hashes the new password before invoking its database procedure. User-facing notifications are delivered with react-toastify.'), h2('6.2 Profile and File Management'), P('Profile pages comprise account overview, personal/contact/address/bank cards, account security and About Me editing. The profile route provides lookup endpoints and an IFSC verification endpoint. Profile image uploads are restricted in the route to PNG/JPG and written under a user UUID directory using the repository path returned from SQL Server. Existing display-picture files are removed before replacement.'), h2('6.3 Package and Payment Module'), P('The dashboard fetches packages through the backend and uses package cards/modal components. The payment controller uses Cashfree SDK server-side order creation. The frontend includes Cashfree JavaScript dependencies and payment success/failure routes. The inspected order-history page currently contains a local array and Excel export function; it is therefore a UI prototype rather than evidence of a live order-history API.'), PageBreak()]

story += [title('6. IMPLEMENTATION MODULES CONTINUED'), h2('6.4 Referral and Network Module'), P('After protected signup-related referral assignment, the backend can retrieve a direct/indirect referral list and an up-to-level-2 network payload. Network UI components render team dashboard cards, package distribution and registration-trend charts, tree controls, zoom/pan support and a genealogy tree. Referral UI includes a profile card, shareable referral link, QR code, statistics, rewards/tips and data table. Server-side procedure documentation specifies search over user ID, name and registration date and filters for referral data.'), h2('6.5 Course and Earnings Presentation'), P('The frontend exposes My Courses, Course Player, earnings summary/history/wallet and withdrawal modal components. The CoursePlayer file declares mockCourseData, and the earnings/order component group provides formatted demonstration cards, tables and charts without inspected corresponding backend routes. These pages are valuable interface work, but their values and curriculum should not be interpreted as confirmed live SQL data.'), h2('6.6 KYC Module'), P('The KYC form selects the identity proof type and presents dynamic document requirements from rules configuration. Basic server validation covers personal names, PAN, supported proof formats and file presence. The Python worker\'s quality decision can be represented as: pass = (width >= minimum) AND (height >= minimum) AND (Laplacian variance >= minimum) AND (dark-pixel ratio <= maximum) AND (light-pixel ratio <= maximum). Thresholds are loaded from rules.json; this report intentionally does not invent data-quality accuracy metrics.'), PageBreak()]

story += [title('7. SECURITY AND VALIDATION'), table([['Area','Verified implementation'],['Passwords','bcrypt hashing before registration/password-reset stored-procedure calls.'],['Session authentication','JWT verification middleware reads Bearer token or cookie, checks signature and exposes decoded identity.'],['Google authentication','Google OAuth client verifies ID token with configured client ID.'],['Authorization','Protected API routes are used for profile retrieval/editing, referral assignment/listing, network, payment order creation and KYC.'],['Input/data validation','Database procedure return codes; KYC basic validator; client-side rule configuration; multer MIME filters.'],['Sensitive document protection','Aadhaar OCR/QR masking in worker; encryption utility exists for AES-256-CBC encryption/decryption of referral-related user ID values.'],['Configuration','Environment variables configure database, JWT, OAuth, SMTP, payment, RabbitMQ and service values without hard-coding reportable secrets.'],['Logging/errors','Winston logger and controller error handling are used throughout key workflows.']], [5*cm,11*cm]), P('Security limitations observed in code are not disguised: the payment webhook controller does not verify a Cashfree signature, the KYC webhook has no inspected service-to-service authentication, and frontend super-admin routing is not wrapped in the standard protection component. These are identified implementation boundaries, not claims of secure production deployment.'), PageBreak()]

story += [title('8. SOFTWARE TESTING AND VERIFICATION'), P('No automated test folder or unit/integration test script is present in the inspected repository. Verification was therefore performed at code and build level, supplemented by a successful production frontend build. The following test cases are suitable for operational validation; results marked “verified by inspection” reflect observable route/controller/component wiring, not a live production test execution.'), table([['Test case','Expected result','Status'],['Frontend production build','Vite transforms and emits production assets.','Passed in workspace'],['Unauthenticated protected API request','JWT middleware should reject absent/invalid token.','Verified by inspection'],['KYC unsupported file','Multer route rejects MIME types outside JPEG/PNG/PDF.','Verified by inspection'],['Blurred/low-quality KYC image','Worker rejects if quality threshold fails and deletes temporary folder.','Verified by inspection'],['Aadhaar masking failure','Worker rejects if OCR cannot identify sufficient digit groups.','Verified by inspection'],['Successful KYC task','Worker moves files, updates KYC state and posts webhook.','Verified by inspection'],['Cashfree order initiation','Controller validates contact details, calls procedure then payment SDK.','Verified by inspection'],['Payment event processing','Webhook maps success/failed state into payment procedure.','Verified by inspection']], [5.3*cm,7.3*cm,3.4*cm]), h2('8.1 Build Observation'), P('The frontend build completed successfully. The bundler emitted a warning about a large JavaScript chunk and a direct-eval warning originating from the ExcelJS dependency bundle. These are build observations, not runtime failure claims.'), PageBreak()]

def screen_page(n, label, detail):
    story.extend([title(f'9. APPLICATION WALKTHROUGH - {n}'), P(detail), Spacer(1,.25*cm), ScreenshotBox(label, 'Insert a full browser capture showing '+detail, 330), P(f'Figure {n+1}: {label}.', 'Cap'), PageBreak()])

screen_page(1,'LOGIN PAGE','the login form, Google sign-in option, navigation to registration/forgot password, and EDUVORA branding.')
screen_page(2,'USER REGISTRATION PAGE','the registration form with full name, email, mobile, password and referral-code fields.')
screen_page(3,'DASHBOARD AND PACKAGE CARDS','the authenticated dashboard with active package cards and package-comparison/details interaction.')
screen_page(4,'COMPLETE PROFILE PAGE','the multi-section personal, contact, address and bank-information form, including field validation controls.')
screen_page(5,'MY PROFILE PAGE','profile header, account overview and profile/edit cards for the authenticated user.')
screen_page(6,'REFERRAL PAGE','referral link, generated QR-code card, referral statistics and referral table.')
screen_page(7,'MY NETWORK PAGE','team statistics, charts, tree search/zoom controls and the genealogy network tree.')
screen_page(8,'PACKAGE PAYMENT INITIATION','a selected EDUVORA package and the payment action before Cashfree checkout.')
screen_page(9,'KYC VERIFICATION PAGE','identity-proof selection, PAN and document fields, upload widgets, consent/review and KYC status.')
screen_page(10,'COURSE PLAYER PAGE','the current course-player layout with video/content area and expandable mock curriculum sidebar; label it as interface prototype data.')
screen_page(11,'ORDERS PAGE','the current order table, filters and Excel export control; label the displayed rows as current frontend demo data.')
screen_page(12,'EARNINGS PAGE','summary/history/wallet tabs and charts/cards; label this as current frontend presentation data unless a live backend source is added.')

story += [title('10. CHALLENGES AND LIMITATIONS'), h2('10.1 Integration Boundaries'), P('The system spans JavaScript and Python runtimes plus SQL Server, RabbitMQ, Cashfree, Google OAuth, SMTP and file repositories. The KYC workflow therefore depends on shared configuration and compatible path access between the Node API and Python worker. The Node publisher constructs a Celery protocol message through RabbitMQ\'s management HTTP API rather than an AMQP library, which is a deliberate cross-runtime integration detail requiring the RabbitMQ management endpoint.'), h2('10.2 Implementation Limitations'), *bullets(['Course playback and curriculum are currently mock data in CoursePlayer; no inspected API supplies enrolment/course content.', 'Orders and earnings screens contain static/local display data; no matching backend order-history, wallet, commission or withdrawal endpoints are exposed.', 'KYC accepts PDF MIME type but the Python quality checker uses cv2.imread, which cannot load a PDF as an image; a PDF may consequently fail worker quality processing.', 'The worker callback URL is fixed to a localhost address in tasks.py, limiting deployment portability unless configuration is changed.', 'KYC status logic has a potentially confusing interim state: submission procedure documentation says it sets IsKYCVerified while worker processing can still later reject the request.', 'No automated tests, CI pipeline, deployment configuration or database migration scripts were found.']), PageBreak()]

story += [title('11. CONCLUSION'), P('EDUVORA demonstrates a substantial web-development architecture centred on authenticated account workflows, SQL Server stored-procedure integration, referral relationships, package-payment initiation and an asynchronous identity-document pipeline. Its strongest technically verified contribution is the KYC flow: it separates immediate web-request handling from heavier document validation through RabbitMQ and Celery, adds image-quality checks and Aadhaar masking, and uses controlled temporary/permanent storage transitions.'), P('The project also provides a broad and polished React interface for profile, referral, network, package, course, order and earnings experiences. A submission should distinguish this interface scope from the live backend scope: profile, referral, network, packages, payment initiation and KYC have visible route/controller implementations, while course curriculum, order history and earnings values remain presentation-stage data in the inspected codebase.'), h2('11.1 Future Enhancements'), *bullets(['Add secured live APIs and SQL procedures for purchased courses, course progress, orders, commissions, wallet transactions and withdrawals.', 'Replace mock course/order/earnings data with protected server queries and apply user-level authorization.', 'Verify Cashfree webhook signatures and authenticate the internal KYC callback.', 'Make worker callback URL, OCR binary path and storage locations environment-configurable for deployment.', 'Handle PDF KYC documents with an explicit rasterisation/extraction path or restrict worker-bound image uploads to supported formats.', 'Add unit, integration and end-to-end tests, database migrations, CI and deployment documentation.', 'Audit the super-admin route and enforce verified role checks on both client navigation and server APIs.']), PageBreak()]

story += [title('12. BIBLIOGRAPHY'), table([['Source','Use in this report'],['EDUVORA backend/brain.md','Database schema and stored-procedure documentation.'],['EDUVORA backend source','Routes, controllers, middleware, utilities, payment/KYC integrations and environment-variable categories.'],['EDUVORA frontend source','Routes, Redux state, screens, components, static-data boundaries and build configuration.'],['EDUVORA kyc-python-worker source','Celery task, RabbitMQ configuration, image quality, Aadhaar masking and SQL repository logic.'],['Package manifests and lockfiles','Verified frameworks and library dependencies.'],['Reference PDF: AI Career Prep Platform Report','Section order, academic tone, A4 report structure, certificate/abstract/acknowledgement/TOC pattern and screenshot convention.']], [6.5*cm,9.5*cm]), Spacer(1,1*cm), P('Prepared for submission by Indrasish Biswas, Roll / Registration No. 24E102B91, B.Tech CSE.', 'Cap')]

doc=SimpleDocTemplate(OUT,pagesize=A4,rightMargin=2*cm,leftMargin=2*cm,topMargin=1.8*cm,bottomMargin=2.1*cm,title='EDUVORA Project Report',author='Indrasish Biswas')
doc.build(story,onFirstPage=footer,onLaterPages=footer)
print(OUT)
