import swaggerUi from 'swagger-ui-express';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read the autogenerated swagger file
const swaggerOutputPath = path.join(__dirname, 'swagger-output.json');
let specs = {};
try {
  specs = JSON.parse(readFileSync(swaggerOutputPath, 'utf-8'));
} catch (error) {
  console.log("Could not load swagger-output.json. Please run swagger.autogen.js first.");
}

export const setupSwagger = (app) => {
  app.use('/swagger', swaggerUi.serve, swaggerUi.setup(specs, {
    customCss: '.swagger-ui .topbar { display: none }',
    customSiteTitle: "EDUVORA API Docs"
  }));
};
