const EmailEvents = {
    REGISTER_OTP: 1,
    FORGOT_PASSWORD_OTP: 2,
    WELCOME: 3,
    PASSWORD_RESET_SUCCESS: 4,
    PASSWORD_CHANGED_BY_ADMIN: 5,
    ACCOUNT_LOCKED: 6,
    ACCOUNT_REACTIVATED: 7,
    KYC_SUBMITTED: 8,
    KYC_UNDER_REVIEW: 9,
    KYC_APPROVED: 10,
    KYC_REJECTED: 11,
    KYC_RESUBMISSION_REQUIRED: 12
};

export default EmailEvents;