import logoImg from '../assets/images/Eduvora.png';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

export const exportToExcel = async ({ data, fileName, columns, sheetName = 'Data' }) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(sheetName);

  // 1. Fetch logo and convert to base64
  let base64Logo = '';
  try {
    const response = await fetch(logoImg);
    const blob = await response.blob();
    base64Logo = await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    console.error("Failed to load logo", error);
  }

  // 2. Add Logo to Excel if available
  if (base64Logo) {
    // extract base64 data correctly (strip off "data:image/png;base64,")
    const base64Data = base64Logo.split(',')[1];
    
    if (base64Data) {
      const imageId = workbook.addImage({
        base64: base64Data,
        extension: 'png',
      });
      // Add image to top left
      worksheet.addImage(imageId, {
        tl: { col: 0, row: 0 },
        ext: { width: 145, height: 78 } // 3.83 cm x 2.07 cm
      });
      
      // Add empty rows to push table data below the logo
      worksheet.addRow([]);
      worksheet.addRow([]);
      worksheet.addRow([]);
      worksheet.addRow([]);
    }
  }

  // 3. Title
  const titleRow = worksheet.addRow([fileName]);
  titleRow.font = { size: 16, bold: true, color: { argb: 'FF1A1446' } };
  worksheet.mergeCells(titleRow.number, 1, titleRow.number, columns.length);
  worksheet.addRow([]); // empty row

  // 4. Add Table Headers
  const headerRow = worksheet.addRow(columns.map(col => col.header));
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4F3BF3' } // Eduvora brand color
    };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
  });

  // 5. Add Data
  data.forEach(item => {
    const rowValues = columns.map(col => {
      if (col.format) return col.format(item);
      return item[col.key] ?? '';
    });
    worksheet.addRow(rowValues);
  });
  
  // 6. Set Column Widths (do it after data to avoid issues)
  worksheet.columns = columns.map(col => ({ width: col.width || 20 }));

  // 7. Add Disclaimer
  worksheet.addRow([]); // empty row
  const disclaimerText = "Disclaimer: This document is generated by Eduvora. The data provided herein is for informational purposes only and is subject to change without notice.";
  const lastRowIndex = worksheet.lastRow.number + 1;
  const disclaimerRow = worksheet.addRow([disclaimerText]);
  
  // merge cells for disclaimer based on number of columns
  worksheet.mergeCells(lastRowIndex, 1, lastRowIndex, columns.length);
  const disclaimerCell = disclaimerRow.getCell(1);
  disclaimerCell.font = { italic: true, color: { argb: 'FF666666' } };
  disclaimerCell.alignment = { wrapText: true, vertical: 'top', horizontal: 'left' };
  disclaimerRow.height = 30; // make room for wrapped text

  // 8. Save file
  const buffer = await workbook.xlsx.writeBuffer();
  saveAs(new Blob([buffer]), `${fileName}.xlsx`);
};
